server:
  port: 8181
  servlet:
    context-path: /api

spring:
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    driver-class-name: org.h2.Driver
    platform: h2
    initialization-mode: always
    url: jdbc:h2:mem:world
    username: sa
    password:
